name: dash
description: App for DASH
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  speech_to_text: ^6.1.1
  roslibdart: ^0.0.1-dev+4
  flutter_tts: ^3.0.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Arimo
      fonts:
        - asset: fonts/Arimo/Arimo-Regular.ttf
        - asset: fonts/Arimo/Arimo-Medium.ttf
        - asset: fonts/Arimo/Arimo-Bold.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-Medium.ttf
        - asset: fonts/Poppins/Poppins-Bold.ttf
    - family: PTMono
      fonts:
        - asset: fonts/PT_Mono/PTMono-Regular.ttf
